# Generated by Django 5.1.7 on 2025-04-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('anons', models.CharField(max_length=250, verbose_name='anons')),
                ('text', models.TextField(verbose_name='text')),
                ('date', models.DateTimeField(verbose_name='date')),
            ],
        ),
    ]
